services:
  - type: web
    name: symfony-project
    env: php
    phpVersion: 8.2.20
    buildCommand: "composer install --optimize-autoloader --no-dev"
    startCommand: "php -S 0.0.0.0:$PORT -t public/"
    envVars:
      - key: APP_ENV
        value: prod
      - key: APP_DEBUG
        value: 0
      - key: APP_SECRET
        generateValue: true